# Project information
site_name: "Pilot Library"
site_description: "Documentation for Pilot Project"
site_url: "https://kansalmohit19.github.io/pilot-library/"

# Repository info (adds edit/view on GitHub buttons)
repo_name: "pilot-library"
repo_url: "https://github.com/kansalmohit19/pilot-library"

# Theme settings
theme:
  name: "material"
  language: 'en'
  icon:
    logo: material/account-tie-hat
  palette:
    primary: 'black'
    accent: 'deep orange'
  font:
    text: 'Roboto'
    code: 'JetBrains Mono'

# Navigation
nav:
  - Overview: index.md
  - Sample Library:
      - Guide: sample-library.md
  - Location Library:
      - Guide: location-library.md
  - License: license.md

# Markdown extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - tables
  - toc:
      permalink: true